/* ----Warning-----
These values were roughly manually sifted through
Otherwise it can end up with stuff like Měna: ["Převod do jednotek SI"]
Také jsou přidané pár custom written properties: [Jméno (Nahradilo různé vlastnosti na jména)]
*/
export const queryEntityProperties = {
    "Člověk": ["Bydliště","Choť","Datum křtu","Datum narození","Datum pohřbu nebo kremace","Datum úmrtí","Dílo","Dítě","Hmotnost","Jméno","Matka","Místo narození","Místo působení","Místo úmrtí","Národnost","Období působení","Obrázek","Otec","Ovlivněn (kým)","Ovládané jazyky","Pohlaví","Povolání","Pseudonym","Přezdívka","Příjmení","Příčina smrti","Rodné jméno","Sourozenec","Stranická příslušnost","Státní občanství","Ve funkci","Vyznání","Významná osoba","Výška","Zaměstnavatel","Zaměření","Zdravotní postižení","Zkráceně","Způsob smrti","Člen (čeho)","Škola","Životní partner"],
    "Budova": ["Architekt","Architektonický styl","Barva","Do","Kód Emporis","Kód Structurae","Nachází se v administrativní jednotce","Nadzemní podlaží","Název","Nemá část","Oficiální web","Plná poštovní adresa","Podzemní podlaží","Použitý materiál","Poštovní směrovací číslo","Skládá se z","Stav užívání","Stát","Tvar","Ulice","Uživatel budovy","Zeměpisné souřadnice","Zhotovitel"],
    "Státní útvar": ["Gini koeficient","Diplomatický vztah","Dluh ústřední vlády jako procento HDP","Doména nejvyššího řádu","Erb","Forma vlády","Hlava státu","Hlavní město","Hraničí s","Hymna","Index lidského rozvoje", "Kontinent","Kód země (ISO 3166-1 numeric)","Mapa polohy","Maritime identification digits","Mezinárodní telefonní předvolba","Měna","Nahrávka výslovnosti","Název","Nejjižnější bod","Nejnižší bod","Nejsevernější bod","Nejvyšší bod","Nejvýchodnější bod","Nejzápadnější bod","Nižší správní celky","Obrázek erbu","Obrázek vlajky","Oficiální web","Plošná výměra","Pojmenováno po","Počet obyvatel","Představitel","Strana silničního provozu","Stát","Užívaný jazyk","Vlajka","Vrcholný orgán soudní moci","Zeměpisné souřadnice","Úřední jazyk","Časové pásmo","Člen (čeho)"],
    "Bydliště": ["Architekt","Geografický tvar","Nejjižnější bod","Nejsevernější bod","Nejvýchodnější bod","Nejzápadnější bod","Plná poštovní adresa","Plošná výměra","Stát","Tvar","Zeměpisné souřadnice"],
    "Choť": ["Bydliště","Choť","Datum křtu","Datum narození","Datum pohřbu nebo kremace","Datum úmrtí","Dílo","Dítě","Hmotnost","Jméno","Matka","Místo narození","Místo působení","Místo úmrtí","Národnost","Období působení","Obrázek","Otec","Ovládané jazyky","Pohlaví","Povolání","Pseudonym","Přezdívka","Příjmení","Příčina smrti","Rodné jméno","Sourozenec","Stranická příslušnost","Státní občanství","Ve funkci","Vyznání","Významná osoba","Výška","Zaměstnavatel","Zaměření","Zdravotní postižení","Zkráceně","Způsob smrti","Člen (čeho)","Škola","Životní partner"],
    "Datum křtu": ["Den v týdnu"],
    "Datum narození": ["Den v týdnu"],
    "Datum pohřbu nebo kremace": ["Den v týdnu"],
    "Datum úmrtí": ["Den v týdnu"],
    "Dílo": ["Autor","Celé dílo dostupné na","Datum vytvoření / založení","Distribuce","Editor","Hlavní téma díla","Jazyk díla/jména","Místo vzniku","Objednavatel","Obrázek","Ocenění","Postavy","Premiérové vysílání","Sbírka","Sponzor","Zamýšlená cílová skupina","Žánr"],
    "Dítě": [],
    "Hmotnost": ["Značka veličiny"],
    "Jméno při narození": ["Jazyk díla/jména","Jméno v rodném jazyce","Kolínská fonetika","Písmo","V původním jazyce"],
    "Jméno v rodném jazyce": [],
    "Matka": ["Bydliště","Choť","Datum křtu","Datum narození","Datum pohřbu nebo kremace","Datum úmrtí","Dílo","Dítě","Hmotnost","Jméno","Matka","Místo narození","Místo působení","Místo úmrtí","Národnost","Období působení","Obrázek","Otec","Ovlivněn (kým)","Ovládané jazyky","Pohlaví","Povolání","Pseudonym","Přezdívka","Příjmení","Příčina smrti","Rodné jméno","Sourozenec","Stranická příslušnost","Státní občanství","Ve funkci","Vyznání","Významná osoba","Výška","Zaměstnavatel","Zaměření","Zdravotní postižení","Zkráceně","Způsob smrti","Člen (čeho)","Škola","Životní partner"],
    "Místo narození": ["Nachází se v administrativní jednotce","Obrázek","Plná poštovní adresa","Stát","Zeměpisné souřadnice"],
    "Místo působení": ["Nachází se v administrativní jednotce","Nadmořská výška","Stát","Zeměpisné souřadnice"],
    "Místo úmrtí": [],
    "Národnost": ["Počet obyvatel","Vyznání"],
    "Období působení": [],
    "Obrázek": ["Datum vytvoření / založení","Tvůrce","Výška","Zobrazuje","Šířka","Žánr"],
    "Otec": ["Bydliště","Choť","Datum křtu","Datum narození","Datum pohřbu nebo kremace","Datum úmrtí","Dítě","Hmotnost","Jméno","Matka","Místo narození","Místo působení","Místo úmrtí","Národnost","Období působení","Obrázek","Otec","Ovlivněn (kým)","Ovládané jazyky","Pohlaví","Povolání","Pseudonym","Přezdívka","Příjmení","Příčina smrti","Rodné jméno","Sourozenec","Stranická příslušnost","Státní občanství","Ve funkci","Vyznání","Významná osoba","Výška","Zaměstnavatel","Zaměření","Zdravotní postižení","Zkráceně","Způsob smrti","Člen (čeho)","Škola","Životní partner"],
    "Ovlivněn (kým)": [],
    "Ovládané jazyky": ["Mapa rozšíření"],
    "Pohlaví": [],
    "Povolání": ["Mužská varianta štítku","Obor tohoto povolání","Obrázek","Ženská varianta štítku"],
    "Pseudonym": [],
    "Přezdívka": [],
    "Příjmení": ["Jazyk díla/jména","Kolínská fonetika","Písmo","V původním jazyce"],
    "Příčina smrti": [],
    "Rodné jméno": ["Identické příjmení","Jazyk díla/jména","Jmeniny","Kolínská fonetika","Nahrávka výslovnosti","Písmo","Rodné jméno druhého pohlaví","V původním jazyce"],
    "Sourozenec": [],
    "Stranická příslušnost": ["Datum vytvoření / založení","Datum zániku","Fax","Generální ředitel","Logo","Motto","Oblast působnosti","Obrázek","Oficiální web","Politické směřování","Počet členů","Předseda","Sídlo","Telefonní číslo","Zakladatel"],
    "Státní občanství": [],
    "Ve funkci": ["Organizace řízená z této funkce","Zahrnuje"],
    "Vyznání": [],
    "Významná osoba": [],
    "Výška": ["Značka veličiny"],
    "Zaměstnavatel": [],
    "Zaměření": [],
    "Zdravotní postižení": ["Příznaky","Zasahuje"],
    "Zkráceně": [],
    "Způsob smrti": [],
    "Člen (čeho)": [],
    "Škola": ["Počet studentů","Zaměření"],
    "Životní partner": ["Bydliště","Choť","Datum křtu","Datum narození","Datum pohřbu nebo kremace","Datum úmrtí","Dílo","Dítě","Hmotnost","Jméno","Matka","Místo narození","Místo působení","Místo úmrtí","Národnost","Období působení","Obrázek","Otec","Ovlivněn (kým)","Ovládané jazyky","Pohlaví","Povolání","Pseudonym","Přezdívka","Příjmení","Příčina smrti","Rodné jméno","Sourozenec","Stranická příslušnost","Státní občanství","Ve funkci","Vyznání","Významná osoba","Výška","Zaměstnavatel","Zaměření","Zdravotní postižení","Zkráceně","Způsob smrti","Člen (čeho)","Škola","Životní partner"],
    "Architekt": ["Jméno na Twitteru","Logo","Oblast působnosti","Oficiální web","Počet odběratelů na sociálních sítích","Stát","Telefonní číslo","Člen (čeho)"],
    "Architektonický styl": [],
    "Barva": [],
    "Do": ["Den v týdnu"],
    "Kategorie na Commons": ["Téma kategorie"],
    "Kód Emporis": [],
    "Kód Structurae": [],
    "Nachází se v administrativní jednotce": ["Facebook Places ID","Datum vytvoření / založení","Datum zániku","Míra nezaměstnanosti","Na území současného administrativního celku","Nachází se v administrativní jednotce","Nejjižnější bod","Nejsevernější bod","Nejvýchodnější bod","Nejzápadnější bod","Nižší správní celky","Oficiální název","Oficiální symbol","Plošná výměra","Poznávací značka","Počet domácností","Představitel","Seznam památek","Síťové napětí","Věková hranice pro uzavření manželství","Zeměpisné souřadnice"],
    "Nadzemní podlaží": [],
    "Nemá část": [],
    "Plná poštovní adresa": ["Nachází se v administrativní jednotce","Stát"],
    "Podzemní podlaží": [],
    "Použitý materiál": ["Charakterizováno (čím)","Emisivita","Uhlíková stopa"],
    "Poštovní směrovací číslo": [],
    "Skládá se z": [],
    "Stav užívání": [],
    "Stát": ["Facebook Places ID","Gini koeficient","Datum vytvoření / založení","Datum zániku","Diplomatický vztah","Dluh ústřední vlády jako procento HDP","Doména nejvyššího řádu","Forma vlády","Hlava státu","Hlavní město","Hraničí s","Hymna","Index lidského rozvoje","Kontinent","Kód země (ISO 3166-1 numeric)","Kód země podle Mezinárodního olympijského výboru","Mapa polohy","Maritime identification digits","Mezinárodní telefonní předvolba","Míra nezaměstnanosti","Měna","Na území současného administrativního celku","Nachází se v administrativní jednotce","Nahrávka výslovnosti","Nejjižnější bod","Nejnižší bod","Nejsevernější bod","Nejvyšší bod","Nejvýchodnější bod","Nejzápadnější bod","Nižší správní celky","Obrázek erbu","Obrázek vlajky","Oficiální název","Oficiální symbol","Oficiální web","Plošná výměra","Pojmenováno po","Poznávací značka","Počet domácností","Počet obyvatel","Seznam památek","Strana silničního provozu","Síťové napětí","Užívaný jazyk","Vlajka","Vrcholný orgán soudní moci","Věková hranice pro uzavření manželství","Zeměpisné souřadnice","Úřední jazyk","Člen (čeho)"],
    "Tvar": [],
    "Ulice": ["Délka","Nachází se v administrativní jednotce","Stát"],
    "Uživatel budovy": [],
    "Zeměpisné souřadnice": [],
    "Zhotovitel": ["Jméno na Twitteru","Logo","Motto","Oblast působnosti","Oficiální web","Počet odběratelů na sociálních sítích","Počet zaměstnanců","Předseda","Sídlo","Telefonní číslo","Vlastník","Zakladatel"],
    "Gini koeficient": [],
    "ID relace OpenStreetMap": [],
    "Diplomatický vztah": ["Do"],
    "Dluh ústřední vlády jako procento HDP": [],
    "Doména nejvyššího řádu": [],
    "Erb": ["ISO 15924 číslo","Datum vytvoření / založení"],
    "Forma vlády": [],
    "Hlava státu": ["ID na Facebooku","Akademický titul","Bydliště","Choť","Datum narození","Datum úmrtí","Držitel úřadu","Dítě","E-mail","Hmotnost","Jméno na Instagramu","Jméno na Twitteru","Jméno v kaně","Jméno v rodném jazyce","Krevní skupina","Matka","Místo narození","Místo působení","Nominace na","Národnost","Obrázek","Ocenění","Oficiální blog","Oficiální web","Otec","Ovládané jazyky","Pohlaví","Používaná ruka","Povolání","Počet dětí","Pseudonym","Přezdívka","Příbuzný","Sourozenec","Stranická příslušnost","Státní občanství","Ve funkci","Vyznání","Výška","Zaměření","Člen (čeho)","Škola"],
    "Hlavní město": ["Datum vytvoření / založení","Je vybaveno (čím)","Mapa polohy","Místní telefonní předvolba","Na vodním toku či ploše nebo u ní","Nachází se v administrativní jednotce","Nadmořská výška","Nižší správní celky","Obrázek","Obrázek erbu","Obrázek vlajky","Partnerské město","Plná poštovní adresa","Plošná výměra","Počet obyvatel","Stát","Zeměpisné souřadnice"],
    "Hraničí s": [],
    "Hymna": ["Autor","Autor textu","Datum vytvoření / založení","Doba trvání","Hudební motiv","Hudební úryvek nebo citace","Jazyk díla/jména","Modifikovaná verze (čeho)","Má melodii","Místo děje","Odvozené dílo","Označení tempa","Producent","Skladatel","Stav autorských práv","Tónina","Užívá text","Údery za minutu","Žánr"],
    "Identifikátor GeoNames": [],
    "Index lidského rozvoje": [],
    "Kontinent": ["Geografický tvar","Kód M.49","Plošná výměra","Zeměpisné souřadnice"],
    "Kód země (ISO 3166-1 numeric)": [],
    "Kód země podle Mezinárodního olympijského výboru": [],
    "Mapa polohy": ["Měřítko","Tvůrce"],
    "Maritime identification digits": [],
    "Mezinárodní telefonní předvolba": [],
    "Měna": ["Popis znaku měny"],
    "Nahrávka výslovnosti": [],
    "Nejjižnější bod": [],
    "Nejnižší bod": [],
    "Nejsevernější bod": [],
    "Nejvyšší bod": [],
    "Nejvýchodnější bod": [],
    "Nejzápadnější bod": [],
    "Nižší správní celky": ["Míra nezaměstnanosti","Na území současného administrativního celku","Nachází se v administrativní jednotce","Nejjižnější bod","Nejsevernější bod","Nejvýchodnější bod","Nejzápadnější bod","Nižší správní celky","Oficiální název","Oficiální symbol","Plošná výměra","Zeměpisné souřadnice"],
    "Obrázek erbu": [],
    "Obrázek vlajky": [],
    "Oficiální web": ["URL","Datum vytvoření / založení","Správce","Vlastník"],
    "Plošná výměra": ["Značka veličiny"],
    "Pojmenováno po": ["Oficiální název","Oficiální web","Stát"],
    "Počet obyvatel": [],
    "Představitel": ["Akademický titul","Bydliště","Choť","Datum narození","Datum úmrtí","Držitel úřadu","Dítě","E-mail","Hmotnost","Jméno na Instagramu","Jméno na Twitteru","Jméno v kaně","Jméno v rodném jazyce","Krevní skupina","Matka","Místo narození","Místo působení","Nominace na","Národnost","Obrázek","Ocenění","Oficiální blog","Oficiální web","Organizace řízená z této funkce","Otec","Ovládané jazyky","Pohlaví","Používaná ruka","Povolání","Počet dětí","Pseudonym","Přezdívka","Příbuzný","Sourozenec","Stranická příslušnost","Státní občanství","Ve funkci","Vyznání","Výška","Zaměření","Člen (čeho)","Škola"],
    "Strana silničního provozu": [],
    "Užívaný jazyk": ["Gramatická osoba","Mapa rozšíření","Má gramatický rod","Používá gramatický pád","Používá slovesný způsob","Regulátor jazyka","Stát"],
    "Vlajka": ["Identifikátor Flags of the World"],
    "Vrcholný orgán soudní moci": ["Datum vytvoření / založení"],
    "Úřední jazyk": ["Gramatická osoba","Mapa rozšíření","Má gramatický rod","Používá gramatický pád","Používá slovesný způsob","Používá velká písmena pro","Počet mluvčích","Regulátor jazyka","Stát"],
    "Časové pásmo": ["ICS kód","Posun oproti UTC"]
}

export const queryVariableInfo = {
    "Člověk": {id:"wd:Q5"},
    "Budova": {id:"wd:Q41176"},
    "Státní útvar": {id:"wd:Q6256"},
    "Jméno": {id:"rdfs:label", valueType:"string"},
    "Název": {id:"rdfs:label", valueType:"string"},
    "Bydliště": {id:"wdt:P551", valueType:"string"},
    "Choť": {id:"wdt:P26", valueType:"string"},
    "Datum křtu": {id:"wdt:P1636", valueType:"date"},
    "Datum narození": {id:"wdt:P569", valueType:"date"},
    "Datum pohřbu nebo kremace": {id:"wdt:P4602", valueType:"date"},
    "Datum úmrtí": {id:"wdt:P570", valueType:"date"},
    "Dílo": {id:"wdt:P800", valueType:"string"},
    "Dítě": {id:"wdt:P40", valueType:"string"},
    "Hmotnost": {id:"wdt:P2067", valueType:"number"},
    "Jméno při narození": {id:"wdt:P1477", valueType:"string"},
    "Jméno v rodném jazyce": {id:"wdt:P1559", valueType:"string"},
    "Matka": {id:"wdt:P25", valueType:"string"},
    "Místo narození": {id:"wdt:P19", valueType:"string"},
    "Místo působení": {id:"wdt:P937", valueType:"string"},
    "Místo úmrtí": {id:"wdt:P20", valueType:"string"},
    "Národnost": {id:"wdt:P172", valueType:"string"},
    "Období působení": {id:"wdt:P1317", valueType:"date"},
    "Obrázek": {id:"wdt:P18", valueType:"image"},
    "Otec": {id:"wdt:P22", valueType:"string"},
    "Ovlivněn (kým)": {id:"wdt:P737", valueType:"string"},
    "Ovládané jazyky": {id:"wdt:P1412", valueType:"string"},
    "Pohlaví": {id:"wdt:P21", valueType:"string"},
    "Povolání": {id:"wdt:P106", valueType:"string"},
    "Pseudonym": {id:"wdt:P742", valueType:"string"},
    "Přezdívka": {id:"wdt:P1449", valueType:"string"},
    "Příjmení": {id:"wdt:P734", valueType:"string"},
    "Příčina smrti": {id:"wdt:P509", valueType:"string"},
    "Rodné jméno": {id:"wdt:P735", valueType:"string"},
    "Sourozenec": {id:"wdt:P3373", valueType:"string"},
    "Stranická příslušnost": {id:"wdt:P102", valueType:"string"},
    "Státní občanství": {id:"wdt:P27", valueType:"string"},
    "Ve funkci": {id:"wdt:P39", valueType:"string"},
    "Vyznání": {id:"wdt:P140", valueType:"string"},
    "Významná osoba": {id:"wdt:P3342", valueType:"string"},
    "Výška": {id:"wdt:P2048", valueType:"number"},
    "Zaměstnavatel": {id:"wdt:P108", valueType:"string"},
    "Zaměření": {id:"wdt:P101", valueType:"string"},
    "Zdravotní postižení": {id:"wdt:P1050", valueType:"string"},
    "Zkráceně": {id:"wdt:P1813", valueType:"string"},
    "Způsob smrti": {id:"wdt:P1196", valueType:"string"},
    "Člen (čeho)": {id:"wdt:P463", valueType:"string"},
    "Škola": {id:"wdt:P69", valueType:"string"},
    "Životní partner": {id:"wdt:P451", valueType:"string"},
    "Architekt": {id:"wdt:P84", valueType:"string"},
    "Architektonický styl": {id:"wdt:P149", valueType:"string"},
    "Barva": {id:"wdt:P462", valueType:"string"},
    "Do": {id:"wdt:P582", valueType:"date"},
    "Kategorie na Commons": {id:"wdt:P373", valueType:"string"},
    "Kód Emporis": {id:"wdt:P455", valueType:"number"},
    "Kód Structurae": {id:"wdt:P454", valueType:"number"},
    "Nachází se v administrativní jednotce": {id:"wdt:P131", valueType:"string"},
    "Nadzemní podlaží": {id:"wdt:P1101", valueType:"number"},
    "Nemá část": {id:"wdt:P3113", valueType:"string"},
    "Oficiální web": {id:"wdt:P856", valueType:"link"},
    "Plná poštovní adresa": {id:"wdt:P6375", valueType:"string"},
    "Podzemní podlaží": {id:"wdt:P1139", valueType:"number"},
    "Použitý materiál": {id:"wdt:P186", valueType:"string"},
    "Poštovní směrovací číslo": {id:"wdt:P281", valueType:"number"},
    "Skládá se z": {id:"wdt:P527", valueType:"string"},
    "Stav užívání": {id:"wdt:P5817", valueType:"string"},
    "Stát": {id:"wdt:P17", valueType:"string"},
    "Tvar": {id:"wdt:P1419", valueType:"string"},
    "Ulice": {id:"wdt:P669", valueType:"string"},
    "Uživatel budovy": {id:"wdt:P466", valueType:"string"},
    "Zeměpisné souřadnice": {id:"wdt:P625", valueType:"coordinates"},
    "Zhotovitel": {id:"wdt:P193", valueType:"string"},
    "Gini koeficient": {id:"wdt:P1125", valueType:"number"},
    "ID relace OpenStreetMap": {id:"wdt:P402", valueType:"number"},
    "Diplomatický vztah": {id:"wdt:P530", valueType:"string"},
    "Dluh ústřední vlády jako procento HDP": {id:"wdt:P1689", valueType:"number"},
    "Doména nejvyššího řádu": {id:"wdt:P78", valueType:"string"},
    "Erb": {id:"wdt:P237", valueType:"string"},
    "Forma vlády": {id:"wdt:P122", valueType:"string"},
    "Galerie na Commons": {id:"wdt:P935", valueType:"string"},
    "Hlava státu": {id:"wdt:P35", valueType:"string"},
    "Hlavní město": {id:"wdt:P36", valueType:"string"},
    "Hraničí s": {id:"wdt:P47", valueType:"string"},
    "Hymna": {id:"wdt:P85", valueType:"string"},
    "Identifikátor GeoNames": {id:"wdt:P1566", valueType:"number"},
    "Index lidského rozvoje": {id:"wdt:P1081", valueType:"number"},
    "Kategorie lidí spojených s tímto místem": {id:"wdt:P1792", valueType:"string"},
    "Kategorie lidí zde narozených": {id:"wdt:P1464", valueType:"string"},
    "Kategorie lidí zde pohřbených": {id:"wdt:P1791", valueType:"string"},
    "Kategorie lidí zde zemřelých": {id:"wdt:P1465", valueType:"string"},
    "Kontinent": {id:"wdt:P30", valueType:"string"},
    "Kód FIPS 10-4": {id:"wdt:P901", valueType:"string"},
    "Kód země (ISO 3166-1 alpha-2)": {id:"wdt:P297", valueType:"string"},
    "Kód země (ISO 3166-1 alpha-3)": {id:"wdt:P298", valueType:"string"},
    "Kód země (ISO 3166-1 numeric)": {id:"wdt:P299", valueType:"number"},
    "Kód země podle GS1": {id:"wdt:P3067", valueType:"number"},
    "Kód země podle Mezinárodního olympijského výboru": {id:"wdt:P984", valueType:"string"},
    "Mapa polohy": {id:"wdt:P242", valueType:"image"},
    "Maritime identification digits": {id:"wdt:P2979", valueType:"number"},
    "Mezinárodní telefonní předvolba": {id:"wdt:P474", valueType:"number"},
    "Měna": {id:"wdt:P38", valueType:"string"},
    "Nahrávka výslovnosti": {id:"wdt:P443", valueType:"link"},
    "Nejjižnější bod": {id:"wdt:P1333", valueType:"coordinates"},
    "Nejnižší bod": {id:"wdt:P1589", valueType:"string"},
    "Nejsevernější bod": {id:"wdt:P1332", valueType:"coordinates"},
    "Nejvyšší bod": {id:"wdt:P610", valueType:"string"},
    "Nejvýchodnější bod": {id:"wdt:P1334", valueType:"coordinates"},
    "Nejzápadnější bod": {id:"wdt:P1335", valueType:"coordinates"},
    "Nižší správní celky": {id:"wdt:P150", valueType:"string"},
    "Obrázek erbu": {id:"wdt:P94", valueType:"image"},
    "Obrázek vlajky": {id:"wdt:P41", valueType:"image"},
    "Plošná výměra": {id:"wdt:P2046", valueType:"number"},
    "Pojmenováno po": {id:"wdt:P138", valueType:"string"},
    "Počet obyvatel": {id:"wdt:P1082", valueType:"number"},
    "Představitel": {id:"wdt:P6", valueType:"string"},
    "Strana silničního provozu": {id:"wdt:P1622", valueType:"string"},
    "Užívaný jazyk": {id:"wdt:P2936", valueType:"string"},
    "Vlajka": {id:"wdt:P163", valueType:"string"},
    "Vrcholný orgán soudní moci": {id:"wdt:P209", valueType:"string"},
    "Úřední jazyk": {id:"wdt:P37", valueType:"string"},
    "Časové pásmo": {id:"wdt:P421", valueType:"string"},
    "NDL JPNO": {id:"wdt:P2687", valueType:"number"},
    "OSGR": {id:"wdt:P613", valueType:"string"},
    "Autor": {id:"wdt:P50", valueType:"string"},
    "Celé dílo dostupné na": {id:"wdt:P953", valueType:"link"},
    "Digitální soubor na Commons": {id:"wdt:P996", valueType:"link"},
    "Distribuce": {id:"wdt:P437", valueType:"string"},
    "Délka": {id:"wdt:P2043", valueType:"number"},
    "Editor": {id:"wdt:P98", valueType:"string"},
    "Fyzicky interaguje s": {id:"wdt:P129", valueType:"string"},
    "Geografický tvar": {id:"wdt:P3896", valueType:"link"},
    "Hlavní téma díla": {id:"wdt:P921", valueType:"string"},
    "Identifikátor GNS Unique Feature": {id:"wdt:P2326", valueType:"number"},
    "Incipit": {id:"wdt:P1922", valueType:"string"},
    "Jazyk díla/jména": {id:"wdt:P407", valueType:"string"},
    "Kód M.49": {id:"wdt:P2082", valueType:"number"},
    "Licence": {id:"wdt:P275", valueType:"string"},
    "Moderátor": {id:"wdt:P371", valueType:"string"},
    "Místo": {id:"wdt:P276", valueType:"string"},
    "Nová funkce": {id:"wdt:P751", valueType:"string"},
    "Nástrojové obsazení": {id:"wdt:P870", valueType:"string"},
    "Objednavatel": {id:"wdt:P88", valueType:"string"},
    "Objem": {id:"wdt:P2234", valueType:"number"},
    "Podtitul": {id:"wdt:P1680", valueType:"string"},
    "Postavy": {id:"wdt:P674", valueType:"string"},
    "Použití": {id:"wdt:P366", valueType:"string"},
    "Počet částí uměleckého díla": {id:"wdt:P2635", valueType:"number"},
    "Pracovní název": {id:"wdt:P1638", valueType:"string"},
    "Premiérové vysílání": {id:"wdt:P449", valueType:"string"},
    "Produkční společnost": {id:"wdt:P272", valueType:"string"},
    "Titul": {id:"wdt:P1476", valueType:"string"},
    "Zamýšlená cílová skupina": {id:"wdt:P2360", valueType:"string"},
    "Šířka": {id:"wdt:P2049", valueType:"number"},
    "Žánr": {id:"wdt:P136", valueType:"string"},
    "Datum": {id:"wdt:P585", valueType:"date"},
    "Den v týdnu": {id:"wdt:P2894", valueType:"string"},
    "Doba trvání": {id:"wdt:P2047", valueType:"number"},
    "Datum vytvoření / založení": {id:"wdt:P571", valueType:"date"},
    "Inventární číslo": {id:"wdt:P217", valueType:"string"},
    "Místo vzniku": {id:"wdt:P740", valueType:"string"},
    "Ocenění": {id:"wdt:P166", valueType:"string"},
    "Podle": {id:"wdt:P144", valueType:"string"},
    "Sbírka": {id:"wdt:P195", valueType:"string"},
    "Sponzor": {id:"wdt:P859", valueType:"string"},
    "Tvůrce": {id:"wdt:P170", valueType:"string"},
    "Uhlíková stopa": {id:"wdt:P5991", valueType:"number"},
    "Video soubor": {id:"wdt:P10", valueType:"image"},
    "Dimenze v ISQ": {id:"wdt:P4020", valueType:"string"},
    "Značka veličiny": {id:"wdt:P416", valueType:"string"},
    "Caverphone": {id:"wdt:P3880", valueType:"string"},
    "Soundex": {id:"wdt:P3878", valueType:"string"},
    "Kolínská fonetika": {id:"wdt:P3879", valueType:"number"},
    "Písmo": {id:"wdt:P282", valueType:"string"},
    "V původním jazyce": {id:"wdt:P1705", valueType:"string"},
    "Údajně totéž co": {id:"wdt:P460", valueType:"string"},
    "Počet nemocničních lůžek": {id:"wdt:P6801", valueType:"number"},
    "Počet zaměstnanců": {id:"wdt:P1128", valueType:"number"},
    "Provozovatel": {id:"wdt:P137", valueType:"string"},
    "Urgentní příjem": {id:"wdt:P6855", valueType:"string"},
    "Vlastník": {id:"wdt:P127", valueType:"string"},
    "Nadmořská výška": {id:"wdt:P2044", valueType:"number"},
    "Související riziko": {id:"wdt:P3335", valueType:"string"},
    "Mapa rozšíření": {id:"wdt:P1846", valueType:"image"},
    "Umělecký směr": {id:"wdt:P135", valueType:"string"},
    "Tloušťka": {id:"wdt:P2610", valueType:"number"},
    "Výrobní metoda": {id:"wdt:P2079", valueType:"string"},
    "Zobrazuje": {id:"wdt:P180", valueType:"string"},
    "Mužská varianta štítku": {id:"wdt:P3321", valueType:"string"},
    "Obor tohoto povolání": {id:"wdt:P425", valueType:"string"},
    "Praktikováno (kým)": {id:"wdt:P3095", valueType:"string"},
    "Ženská varianta štítku": {id:"wdt:P2521", valueType:"string"},
    "Identické příjmení": {id:"wdt:P1533", valueType:"string"},
    "Jmeniny": {id:"wdt:P1750", valueType:"string"},
    "Patronymum nebo matronymum": {id:"wdt:P2976", valueType:"string"},
    "Rodné jméno druhého pohlaví": {id:"wdt:P1560", valueType:"string"},
    "ID institutu na ResearchGate": {id:"wdt:P2740", valueType:"string"},
    "ISNI": {id:"wdt:P213", valueType:"string"},
    "LEI": {id:"wdt:P1278", valueType:"string"},
    "OpenCorporates ID": {id:"wdt:P1320", valueType:"string"},
    "Datum zániku": {id:"wdt:P576", valueType:"date"},
    "Držitel úřadu": {id:"wdt:P1308", valueType:"string"},
    "Fax": {id:"wdt:P2900", valueType:"number"},
    "Generální ředitel": {id:"wdt:P169", valueType:"string"},
    "Identifikační číslo zaměstnavatele podle IRS": {id:"wdt:P1297", valueType:"number"},
    "Logo": {id:"wdt:P154", valueType:"image"},
    "Mateřská organizace": {id:"wdt:P749", valueType:"string"},
    "Motto": {id:"wdt:P1451", valueType:"string"},
    "Místo pohřbení": {id:"wdt:P119", valueType:"string"},
    "Oblast působnosti": {id:"wdt:P2541", valueType:"string"},
    "Odvětví": {id:"wdt:P452", valueType:"string"},
    "Organizace řízená z této funkce": {id:"wdt:P2389", valueType:"string"},
    "Politické směřování": {id:"wdt:P1387", valueType:"string"},
    "Počet mandátů v legislativním orgánu": {id:"wdt:P1410", valueType:"number"},
    "Počet členů": {id:"wdt:P2124", valueType:"number"},
    "Prefix DOI": {id:"wdt:P1662", valueType:"number"},
    "Produkuje": {id:"wdt:P1056", valueType:"string"},
    "Provozní ředitel": {id:"wdt:P1789", valueType:"string"},
    "Právní forma": {id:"wdt:P1454", valueType:"string"},
    "Předseda": {id:"wdt:P488", valueType:"string"},
    "Sídlo": {id:"wdt:P159", valueType:"string"},
    "Telefonní číslo": {id:"wdt:P1329", valueType:"number"},
    "Zakladatel": {id:"wdt:P112", valueType:"string"},
    "Autor předmluvy": {id:"wdt:P2679", valueType:"string"},
    "Počet": {id:"wdt:P1114", valueType:"number"},
    "Počet stran": {id:"wdt:P1104", valueType:"number"},
    "Zahrnuje": {id:"wdt:P2670", valueType:"string"},
    "Datum objevu": {id:"wdt:P575", valueType:"date"},
    "Objevitel nebo vynálezce": {id:"wdt:P61", valueType:"string"},
    "EMedicine": {id:"wdt:P673", valueType:"number"},
    "Kód DiseasesDB": {id:"wdt:P557", valueType:"number"},
    "Kód MKN-10": {id:"wdt:P494", valueType:"string"},
    "Kód MKN-9": {id:"wdt:P493", valueType:"number"},
    "Příznaky": {id:"wdt:P780", valueType:"string"},
    "Zasahuje": {id:"wdt:P689", valueType:"string"},
    "ISO 15924 alpha-4 kód": {id:"wdt:P506", valueType:"string"},
    "ISO 15924 číslo": {id:"wdt:P2620", valueType:"number"},
    "Směr psaní": {id:"wdt:P1406", valueType:"string"},
    "Hudební nástroj": {id:"wdt:P1303", valueType:"string"},
    "Počet studentů": {id:"wdt:P2196", valueType:"number"},
    "ID kanálu YouTube": {id:"wdt:P2397", valueType:"string"},
    "ID na Facebooku": {id:"wdt:P2013", valueType:"string"},
    "ID společnosti na LinkedIn": {id:"wdt:P4264", valueType:"number"},
    "URL informací o stavu služby": {id:"wdt:P9138", valueType:"link"},
    "WorldCat Identities ID": {id:"wdt:P7859", valueType:"string"},
    "Aktiva": {id:"wdt:P2403", valueType:"number"},
    "Burza": {id:"wdt:P414", valueType:"string"},
    "Cizí zdroje": {id:"wdt:P2138", valueType:"number"},
    "Dceřiná společnost": {id:"wdt:P355", valueType:"string"},
    "Identifikátor EUTA pro osobu": {id:"wdt:P4534", valueType:"number"},
    "Jméno na Twitteru": {id:"wdt:P2002", valueType:"string"},
    "Obchodní divize": {id:"wdt:P199", valueType:"string"},
    "Oficiální název": {id:"wdt:P1448", valueType:"string"},
    "Popsáno v URL": {id:"wdt:P973", valueType:"link"},
    "Počet odběratelů na sociálních sítích": {id:"wdt:P8687", valueType:"number"},
    "Provozní zisk": {id:"wdt:P3362", valueType:"number"},
    "Tržby": {id:"wdt:P2139", valueType:"number"},
    "Tržní kapitalizace": {id:"wdt:P2226", valueType:"number"},
    "Vlastní kapitál": {id:"wdt:P2137", valueType:"number"},
    "Země původu": {id:"wdt:P495", valueType:"string"},
    "Čistý zisk": {id:"wdt:P2295", valueType:"number"},
    "Člen správní rady": {id:"wdt:P3320", valueType:"string"},
    "Ekvivalentní Wikidata SPARQL dotaz": {id:"wdt:P3921", valueType:"string"},
    "Kategorie kombinuje témata": {id:"wdt:P971", valueType:"string"},
    "Kategorie obsahuje": {id:"wdt:P4224", valueType:"string"},
    "Seznam (čeho)": {id:"wdt:P360", valueType:"string"},
    "Téma kategorie": {id:"wdt:P301", valueType:"string"},
    "Facebook Places ID": {id:"wdt:P1997", valueType:"number"},
    "TGN ID": {id:"wdt:P1667", valueType:"number"},
    "WOEID": {id:"wdt:P1281", valueType:"number"},
    "Kód GNIS": {id:"wdt:P590", valueType:"number"},
    "Kód čínské administrativní jednotky": {id:"wdt:P442", valueType:"number"},
    "Míra nezaměstnanosti": {id:"wdt:P1198", valueType:"number"},
    "Na území současného administrativního celku": {id:"wdt:P3842", valueType:"string"},
    "Nástupce": {id:"wdt:P1366", valueType:"string"},
    "Oficiální symbol": {id:"wdt:P2238", valueType:"string"},
    "Poznávací značka": {id:"wdt:P395", valueType:"string"},
    "Počet domácností": {id:"wdt:P1538", valueType:"number"},
    "Předchůdce": {id:"wdt:P1365", valueType:"string"},
    "Seznam památek": {id:"wdt:P1456", valueType:"string"},
    "Síťové napětí": {id:"wdt:P2884", valueType:"number"},
    "Věková hranice pro uzavření manželství": {id:"wdt:P3000", valueType:"number"},
    "Alexa rank": {id:"wdt:P1661", valueType:"number"},
    "URL": {id:"wdt:P2699", valueType:"link"},
    "Autor (text)": {id:"wdt:P2093", valueType:"string"},
    "Cituje": {id:"wdt:P2860", valueType:"string"},
    "Datum vydání": {id:"wdt:P577", valueType:"date"},
    "Správce": {id:"wdt:P126", valueType:"string"},
    "Vydavatel": {id:"wdt:P123", valueType:"string"},
    "Cíl cesty": {id:"wdt:P1444", valueType:"string"},
    "Dopravní síť": {id:"wdt:P16", valueType:"string"},
    "Počátek cesty": {id:"wdt:P1427", valueType:"string"},
    "Charakterizováno (čím)": {id:"wdt:P1552", valueType:"string"},
    "Emisivita": {id:"wdt:P1295", valueType:"number"},
    "Kód německého okresu": {id:"wdt:P440", valueType:"number"},
    "Úřad vedoucího této organizace": {id:"wdt:P2388", valueType:"string"},
    "Identifikátor Freebase": {id:"wdt:P646", valueType:"string"},
    "Účastník": {id:"wdt:P710", valueType:"string"},
    "Část (čeho)": {id:"wdt:P361", valueType:"string"},
    "Patří k jurisdikci": {id:"wdt:P1001", valueType:"string"},
    "Akademický titul": {id:"wdt:P512", valueType:"string"},
    "E-mail": {id:"wdt:P968", valueType:"string"},
    "Jméno na Instagramu": {id:"wdt:P2003", valueType:"string"},
    "Jméno v kaně": {id:"wdt:P1814", valueType:"string"},
    "Krevní skupina": {id:"wdt:P1853", valueType:"number"},
    "Nominace na": {id:"wdt:P1411", valueType:"string"},
    "Oficiální blog": {id:"wdt:P1581", valueType:"link"},
    "Používaná ruka": {id:"wdt:P552", valueType:"string"},
    "Počet dětí": {id:"wdt:P1971", valueType:"number"},
    "Příbuzný": {id:"wdt:P1038", valueType:"string"},
    "BNF ID": {id:"wdt:P268", valueType:"string"},
    "Banner pro Wikicesty": {id:"wdt:P948", valueType:"image"},
    "Hlavní kategorie tématu": {id:"wdt:P910", valueType:"string"},
    "Identifikátor GND": {id:"wdt:P227", valueType:"number"},
    "Je vybaveno (čím)": {id:"wdt:P912", valueType:"string"},
    "Kód MusicBrainz pro oblast": {id:"wdt:P982", valueType:"string"},
    "Místní telefonní předvolba": {id:"wdt:P473", valueType:"number"},
    "Na vodním toku či ploše nebo u ní": {id:"wdt:P206", valueType:"string"},
    "Otevírací doba": {id:"wdt:P3025", valueType:"string"},
    "Partnerské město": {id:"wdt:P190", valueType:"string"},
    "Parsonův kód": {id:"wdt:P1236", valueType:"string"},
    "VIAF": {id:"wdt:P214", valueType:"number"},
    "Autor textu": {id:"wdt:P676", valueType:"string"},
    "Druh uměleckého díla": {id:"wdt:P7937", valueType:"string"},
    "Explicit": {id:"wdt:P3132", valueType:"string"},
    "Hudební motiv": {id:"wdt:P6686", valueType:"string"},
    "Hudební úryvek nebo citace": {id:"wdt:P6670", valueType:"string"},
    "Identifikátor NLI (Izrael)": {id:"wdt:P949", valueType:"number"},
    "Interpret": {id:"wdt:P175", valueType:"string"},
    "Kód MusicBrainz pro dílo": {id:"wdt:P435", valueType:"string"},
    "Modifikováno (kým)": {id:"wdt:P5202", valueType:"string"},
    "Má melodii": {id:"wdt:P1625", valueType:"string"},
    "Místo děje": {id:"wdt:P840", valueType:"string"},
    "Odehrává se v období": {id:"wdt:P2408", valueType:"number"},
    "Odvozené dílo": {id:"wdt:P4969", valueType:"string"},
    "Označení tempa": {id:"wdt:P1558", valueType:"string"},
    "Partitura": {id:"wdt:P3030", valueType:"image"},
    "Producent": {id:"wdt:P162", valueType:"string"},
    "Skladatel": {id:"wdt:P86", valueType:"string"},
    "Stav autorských práv": {id:"wdt:P6216", valueType:"string"},
    "Takt": {id:"wdt:P3440", valueType:"string"},
    "Tónina": {id:"wdt:P826", valueType:"string"},
    "Užívá text": {id:"wdt:P6439", valueType:"string"},
    "Údery za minutu": {id:"wdt:P1725", valueType:"number"},
    "Číslo IMSLP": {id:"wdt:P839", valueType:"string"},
    "Měřítko": {id:"wdt:P1752", valueType:"number"},
    "ISO 4217": {id:"wdt:P498", valueType:"string"},
    "Fyzikální veličina": {id:"wdt:P111", valueType:"string"},
    "Popis znaku měny": {id:"wdt:P489", valueType:"string"},
    "Převod na jednotku SI": {id:"wdt:P2370", valueType:"number"},
    "Převod na standardní jednotku": {id:"wdt:P2442", valueType:"number"},
    "Značka jednotky": {id:"wdt:P5061", valueType:"string"},
    "Identifikátor Flags of the World": {id:"wdt:P3089", valueType:"string"},
    "Gramatická osoba": {id:"wdt:P5110", valueType:"string"},
    "Má gramatický rod": {id:"wdt:P5109", valueType:"string"},
    "Používá gramatický pád": {id:"wdt:P2989", valueType:"string"},
    "Používá slovesný způsob": {id:"wdt:P3161", valueType:"string"},
    "Regulátor jazyka": {id:"wdt:P1018", valueType:"string"},
    "Uzákoněno": {id:"wdt:P92", valueType:"string"},
    "ISO 639-1": {id:"wdt:P218", valueType:"string"},
    "ISO 639-3": {id:"wdt:P220", valueType:"string"},
    "Kód jazyka pro Wikimedia": {id:"wdt:P424", valueType:"string"},
    "Používá velká písmena pro": {id:"wdt:P6106", valueType:"string"},
    "Počet mluvčích": {id:"wdt:P1098", valueType:"number"},
    "ICS kód": {id:"wdt:P5046", valueType:"number"},
    "Posun oproti UTC": {id:"wdt:P2907", valueType:"number"},
    "Správce standardu": {id:"wdt:P1462", valueType:"string"}
}